version: 0.2
env:
  parameter-store:
    docker_username: /docker_u_name
    docker_password: /docker_password
phases:
  install:
    # runtime-versions:
    #   nodejs: 20
    #   docker: 18
    commands:
        - echo Installing pip
        - curl -O https://bootstrap.pypa.io/get-pip.py
        - python3 get-pip.py
        - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
        - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
        - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        - chmod +x ./kubectl
        - curl -Lo aws-iam-authenticator https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.5.9/aws-iam-authenticator_0.5.9_linux_amd64
        - chmod +x ./aws-iam-authenticator
        - export PATH=$PWD/:$PATH
  pre_build:
    commands:
      - IMAGE="fullstack/python"
      - BUILD_NUMBER=$(cat version)
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 010438506754.dkr.ecr.us-east-1.amazonaws.com
      - export KUBECONFIG=$HOME/.kube/config
  build:
    commands:
      - echo $docker_password | docker login --username $docker_username --password-stdin
      - docker build -t $IMAGE:$BUILD_NUMBER -f Dockerfile .
      - docker tag $IMAGE:$BUILD_NUMBER 010438506754.dkr.ecr.us-east-1.amazonaws.com/$IMAGE:$BUILD_NUMBER
  post_build:
    commands:
      - docker push 010438506754.dkr.ecr.us-east-1.amazonaws.com/$IMAGE:$BUILD_NUMBER
      # - aws eks update-kubeconfig --name my-cluster1
      - aws eks update-kubeconfig --name my-cluster1 --region us-east-1 --kubeconfig $HOME/.kube/config
      - kubectl config get-contexts
      - kubectl get nodes 
      - kubectl get nodes 
      - template=`cat "deployment.yml" | sed "s/latest/$BUILD_NUMBER/g"`
      - echo "$template"
      - echo "$template" | kubectl apply -f -