apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-app
  labels:
    app: two-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-tier-app
  template:
    metadata:
      labels:
        app: two-tier-app
    spec:
      containers:
        - name: two-tier-app
          image: 010438506754.dkr.ecr.us-east-1.amazonaws.com/fullstack/python:latest
          env:
            - name: MYSQL_HOST
              value: mysql        
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DB
              value: "mydb"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"  
              cpu: "100m"       
            limits:
              memory: "256Mi"   
              cpu: "200m"       
