apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - app
      containers:
        - name: my-app
          image: 010438506754.dkr.ecr.us-east-1.amazonaws.com/fullstack/python:latest
          env:
            - name: MYSQL_HOST
              value: mysql        
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DB
              value: "mydb"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"  
              cpu: "100m"       
            limits:
              memory: "256Mi"   
              cpu: "200m"